name: Upload MFAwesome to Pypi

on:
  push:
    branches:
      - main
      - release/*
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    environment:
        name: pypi
        url: https://pypi.org/project/mfawesome/
    runs-on: ubuntu-latest
    permissions:
        id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel build
    - name: Build package
      run: python3 -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        repository-url: https://pypi.org/legacy/
